controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    gimbal_controller:                                    
      type: joint_trajectory_controller/JointTrajectoryController



mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 1.0 # max time between command messages before the vehicle should stop
    front_left_wheel_command_joint_name:  "chassis_TO_front_left_wheel"
    front_right_wheel_command_joint_name: "chassis_TO_front_right_wheel"
    rear_right_wheel_command_joint_name:  "chassis_TO_rear_right_wheel"
    rear_left_wheel_command_joint_name:   "chassis_TO_rear_left_wheel"
    kinematics:
        base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
        wheels_radius: 0.15        
        sum_of_robot_center_projection_on_X_Y_axis: 0.5     # (wheelbase/2) + (track_width/2) = 0.25 + 0.25
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    cmd_vel_topic: "/cmd_vel" 



gimbal_controller:
  ros__parameters:
    joints:
      - gimbal_base_TO_gimbal_yaw_link
      - gimbal_yaw_link_TO_gimbal_pitch_link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5